# production:
#   adapter: postgresql
#   encoding: unicode
#   database: feedbin
#   pool: <%= ENV['DB_POOL'] || 5 %>
#   username: <%= ENV['POSTGRES_USERNAME'] %>
#   password: <%= ENV['POSTGRES_PASSWORD'] %>
#   host: <%= ENV['POSTGRES_HOST'] %>

development:
  adapter: postgresql
  encoding: unicode
  database: feedbin_development
  pool: <%= ENV['DB_POOL'] || 5 %>
  username: <%= ENV['POSTGRES_USERNAME'] %>
  password:
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: feedbin_test
  pool: <%= ENV['DB_POOL'] || 5 %>
  username: <%= ENV['POSTGRES_USERNAME'] %>
  password:
  host: localhost
